export const LOAD_QUESTIONS = 'App/LOAD_QUESTIONS';
export const LOAD_QUESTIONS_SUCCESS = 'App/LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_ERROR = 'App/LOAD_QUESTIONS_ERROR';
export const SUBMIT_ANSWER = 'App/SUBMIT_ANSWER';
